language: python
dist: xenial
services:
  - xvfb
python:
    - "2.7"
install:
  - make requirements
script:
  - make selfcheck
  - make quality
  - make test
  - make validate_translations
notifications:
  email: false
addons:
  firefox: 36.0
